
#include "GUI_cryoTargetController.h"


int32_t tempSetNum = 0;
char strBufNum[NUM_STR_LEN];


void	GUI_CTC_init(void)
{
	GUI_objectListReset();
	
	GUI_objSetHandlerFunc(&GUI_CTC_objAction);
	
	GUI_drawFilledFrame(0, LCD_WIDTH-1, 0, LCD_HEIGHT-1, 0, 0xFFFF, 0x0000);
	GUI_createLabel(LABEL_ID0_HEADER_X0,	LABEL_ID0_HEADER_X1,
									LABEL_ID0_HEADER_Y0,	LABEL_ID0_HEADER_Y1,
									LABEL_ID0_HEADER_BORDER,
									LABEL_ID0_HEADER_MAIN_COLOR,
									LABEL_ID0_HEADER_BORDER_COLOR,
									LABEL_ID0_HEADER_TEXT,
									LABEL_ID0_HEADER_TEXT_COLOR,
									LABEL_ID0_HEADER_TEXT_MARGIN_X,
									LABEL_ID0_HEADER_TEXT_MARGIN_Y,
									LABEL_ID0_HEADER_ACTION_PTR);
	GUI_createLabel(LABEL_ID1_HEADER_SENS_X0,	LABEL_ID1_HEADER_SENS_X1,
									LABEL_ID1_HEADER_SENS_Y0,	LABEL_ID1_HEADER_SENS_Y1,
									LABEL_ID1_HEADER_SENS_BORDER,
									LABEL_ID1_HEADER_SENS_MAIN_COLOR,
									LABEL_ID1_HEADER_SENS_BORDER_COLOR,
									LABEL_ID1_HEADER_SENS_TEXT,
									LABEL_ID1_HEADER_SENS_TEXT_COLOR,
									LABEL_ID1_HEADER_SENS_TEXT_MARGIN_X,
									LABEL_ID1_HEADER_SENS_TEXT_MARGIN_Y,
									LABEL_ID1_HEADER_SENS_ACTION_PTR);
	GUI_createLabel(LABEL_ID2_SENS_1_X0,	LABEL_ID2_SENS_1_X1,
									LABEL_ID2_SENS_1_Y0,	LABEL_ID2_SENS_1_Y1,
									LABEL_ID2_SENS_1_BORDER,
									LABEL_ID2_SENS_1_MAIN_COLOR,
									LABEL_ID2_SENS_1_BORDER_COLOR,
									LABEL_ID2_SENS_1_TEXT,
									LABEL_ID2_SENS_1_TEXT_COLOR,
									LABEL_ID2_SENS_1_TEXT_MARGIN_X,
									LABEL_ID2_SENS_1_TEXT_MARGIN_Y,
									LABEL_ID2_SENS_1_ACTION_PTR);
	GUI_createLabel(LABEL_ID3_SENS_2_X0,	LABEL_ID3_SENS_2_X1,
									LABEL_ID3_SENS_2_Y0,	LABEL_ID3_SENS_2_Y1,
									LABEL_ID3_SENS_2_BORDER,
									LABEL_ID3_SENS_2_MAIN_COLOR,
									LABEL_ID3_SENS_2_BORDER_COLOR,
									LABEL_ID3_SENS_2_TEXT,
									LABEL_ID3_SENS_2_TEXT_COLOR,
									LABEL_ID3_SENS_2_TEXT_MARGIN_X,
									LABEL_ID3_SENS_2_TEXT_MARGIN_Y,
									LABEL_ID3_SENS_2_ACTION_PTR);
	GUI_createLabel(LABEL_ID4_SENS_3_X0,	LABEL_ID4_SENS_3_X1,
									LABEL_ID4_SENS_3_Y0,	LABEL_ID4_SENS_3_Y1,
									LABEL_ID4_SENS_3_BORDER,
									LABEL_ID4_SENS_3_MAIN_COLOR,
									LABEL_ID4_SENS_3_BORDER_COLOR,
									LABEL_ID4_SENS_3_TEXT,
									LABEL_ID4_SENS_3_TEXT_COLOR,
									LABEL_ID4_SENS_3_TEXT_MARGIN_X,
									LABEL_ID4_SENS_3_TEXT_MARGIN_Y,
									LABEL_ID4_SENS_3_ACTION_PTR);
	GUI_createLabel(LABEL_ID5_SENS_4_X0,	LABEL_ID5_SENS_4_X1,
									LABEL_ID5_SENS_4_Y0,	LABEL_ID5_SENS_4_Y1,
									LABEL_ID5_SENS_4_BORDER,
									LABEL_ID5_SENS_4_MAIN_COLOR,
									LABEL_ID5_SENS_4_BORDER_COLOR,
									LABEL_ID5_SENS_4_TEXT,
									LABEL_ID5_SENS_4_TEXT_COLOR,
									LABEL_ID5_SENS_4_TEXT_MARGIN_X,
									LABEL_ID5_SENS_4_TEXT_MARGIN_Y,
									LABEL_ID5_SENS_4_ACTION_PTR);
	GUI_createLabel(LABEL_ID6_SENS_5_X0,	LABEL_ID6_SENS_5_X1,
									LABEL_ID6_SENS_5_Y0,	LABEL_ID6_SENS_5_Y1,
									LABEL_ID6_SENS_5_BORDER,
									LABEL_ID6_SENS_5_MAIN_COLOR,
									LABEL_ID6_SENS_5_BORDER_COLOR,
									LABEL_ID6_SENS_5_TEXT,
									LABEL_ID6_SENS_5_TEXT_COLOR,
									LABEL_ID6_SENS_5_TEXT_MARGIN_X,
									LABEL_ID6_SENS_5_TEXT_MARGIN_Y,
									LABEL_ID6_SENS_5_ACTION_PTR);
	GUI_createLabel(LABEL_ID7_SENS_6_X0,	LABEL_ID7_SENS_6_X1,
									LABEL_ID7_SENS_6_Y0,	LABEL_ID7_SENS_6_Y1,
									LABEL_ID7_SENS_6_BORDER,
									LABEL_ID7_SENS_6_MAIN_COLOR,
									LABEL_ID7_SENS_6_BORDER_COLOR,
									LABEL_ID7_SENS_6_TEXT,
									LABEL_ID7_SENS_6_TEXT_COLOR,
									LABEL_ID7_SENS_6_TEXT_MARGIN_X,
									LABEL_ID7_SENS_6_TEXT_MARGIN_Y,
									LABEL_ID7_SENS_6_ACTION_PTR);
	GUI_createLabel(LABEL_ID8_SENS_7_X0,	LABEL_ID8_SENS_7_X1,
									LABEL_ID8_SENS_7_Y0,	LABEL_ID8_SENS_7_Y1,
									LABEL_ID8_SENS_7_BORDER,
									LABEL_ID8_SENS_7_MAIN_COLOR,
									LABEL_ID8_SENS_7_BORDER_COLOR,
									LABEL_ID8_SENS_7_TEXT,
									LABEL_ID8_SENS_7_TEXT_COLOR,
									LABEL_ID8_SENS_7_TEXT_MARGIN_X,
									LABEL_ID8_SENS_7_TEXT_MARGIN_Y,
									LABEL_ID8_SENS_7_ACTION_PTR);
	GUI_createLabel(LABEL_ID9_SENS_8_X0,	LABEL_ID9_SENS_8_X1,
									LABEL_ID9_SENS_8_Y0,	LABEL_ID9_SENS_8_Y1,
									LABEL_ID9_SENS_8_BORDER,
									LABEL_ID9_SENS_8_MAIN_COLOR,
									LABEL_ID9_SENS_8_BORDER_COLOR,
									LABEL_ID9_SENS_8_TEXT,
									LABEL_ID9_SENS_8_TEXT_COLOR,
									LABEL_ID9_SENS_8_TEXT_MARGIN_X,
									LABEL_ID9_SENS_8_TEXT_MARGIN_Y,
									LABEL_ID9_SENS_8_ACTION_PTR);
	GUI_createLabel(LABEL_ID10_TSET_X0,	LABEL_ID10_TSET_X1,
									LABEL_ID10_TSET_Y0,	LABEL_ID10_TSET_Y1,
									LABEL_ID10_TSET_BORDER,
									LABEL_ID10_TSET_MAIN_COLOR,
									LABEL_ID10_TSET_BORDER_COLOR,
									LABEL_ID10_TSET_TEXT,
									LABEL_ID10_TSET_TEXT_COLOR,
									LABEL_ID10_TSET_TEXT_MARGIN_X,
									LABEL_ID10_TSET_TEXT_MARGIN_Y,
									LABEL_ID10_TSET_ACTION_PTR);
	GUI_createLabel(LABEL_ID11_TCHANGE_X0,	LABEL_ID11_TCHANGE_X1,
									LABEL_ID11_TCHANGE_Y0,	LABEL_ID11_TCHANGE_Y1,
									LABEL_ID11_TCHANGE_BORDER,
									LABEL_ID11_TCHANGE_MAIN_COLOR,
									LABEL_ID11_TCHANGE_BORDER_COLOR,
									LABEL_ID11_TCHANGE_TEXT,
									LABEL_ID11_TCHANGE_TEXT_COLOR,
									LABEL_ID11_TCHANGE_TEXT_MARGIN_X,
									LABEL_ID11_TCHANGE_TEXT_MARGIN_Y,
									LABEL_ID11_TCHANGE_ACTION_PTR);
	GUI_createLabel(LABEL_ID12_SENS_1_NUM_X0,	LABEL_ID12_SENS_1_NUM_X1,
									LABEL_ID12_SENS_1_NUM_Y0,	LABEL_ID12_SENS_1_NUM_Y1,
									LABEL_ID12_SENS_1_NUM_BORDER,
									LABEL_ID12_SENS_1_NUM_MAIN_COLOR,
									LABEL_ID12_SENS_1_NUM_BORDER_COLOR,
									LABEL_ID12_SENS_1_NUM_TEXT,
									LABEL_ID12_SENS_1_NUM_TEXT_COLOR,
									LABEL_ID12_SENS_1_NUM_TEXT_MARGIN_X,
									LABEL_ID12_SENS_1_NUM_TEXT_MARGIN_Y,
									LABEL_ID12_SENS_1_NUM_ACTION_PTR);
	GUI_createLabel(LABEL_ID13_SENS_2_NUM_X0,	LABEL_ID13_SENS_2_NUM_X1,
									LABEL_ID13_SENS_2_NUM_Y0,	LABEL_ID13_SENS_2_NUM_Y1,
									LABEL_ID13_SENS_2_NUM_BORDER,
									LABEL_ID13_SENS_2_NUM_MAIN_COLOR,
									LABEL_ID13_SENS_2_NUM_BORDER_COLOR,
									LABEL_ID13_SENS_2_NUM_TEXT,
									LABEL_ID13_SENS_2_NUM_TEXT_COLOR,
									LABEL_ID13_SENS_2_NUM_TEXT_MARGIN_X,
									LABEL_ID13_SENS_2_NUM_TEXT_MARGIN_Y,
									LABEL_ID13_SENS_2_NUM_ACTION_PTR);
	GUI_createLabel(LABEL_ID14_SENS_3_NUM_X0,	LABEL_ID14_SENS_3_NUM_X1,
									LABEL_ID14_SENS_3_NUM_Y0,	LABEL_ID14_SENS_3_NUM_Y1,
									LABEL_ID14_SENS_3_NUM_BORDER,
									LABEL_ID14_SENS_3_NUM_MAIN_COLOR,
									LABEL_ID14_SENS_3_NUM_BORDER_COLOR,
									LABEL_ID14_SENS_3_NUM_TEXT,
									LABEL_ID14_SENS_3_NUM_TEXT_COLOR,
									LABEL_ID14_SENS_3_NUM_TEXT_MARGIN_X,
									LABEL_ID14_SENS_3_NUM_TEXT_MARGIN_Y,
									LABEL_ID14_SENS_3_NUM_ACTION_PTR);
	GUI_createLabel(LABEL_ID15_SENS_4_NUM_X0,	LABEL_ID15_SENS_4_NUM_X1,
									LABEL_ID15_SENS_4_NUM_Y0,	LABEL_ID15_SENS_4_NUM_Y1,
									LABEL_ID15_SENS_4_NUM_BORDER,
									LABEL_ID15_SENS_4_NUM_MAIN_COLOR,
									LABEL_ID15_SENS_4_NUM_BORDER_COLOR,
									LABEL_ID15_SENS_4_NUM_TEXT,
									LABEL_ID15_SENS_4_NUM_TEXT_COLOR,
									LABEL_ID15_SENS_4_NUM_TEXT_MARGIN_X,
									LABEL_ID15_SENS_4_NUM_TEXT_MARGIN_Y,
									LABEL_ID15_SENS_4_NUM_ACTION_PTR);
	GUI_createLabel(LABEL_ID16_SENS_5_NUM_X0,	LABEL_ID16_SENS_5_NUM_X1,
									LABEL_ID16_SENS_5_NUM_Y0,	LABEL_ID16_SENS_5_NUM_Y1,
									LABEL_ID16_SENS_5_NUM_BORDER,
									LABEL_ID16_SENS_5_NUM_MAIN_COLOR,
									LABEL_ID16_SENS_5_NUM_BORDER_COLOR,
									LABEL_ID16_SENS_5_NUM_TEXT,
									LABEL_ID16_SENS_5_NUM_TEXT_COLOR,
									LABEL_ID16_SENS_5_NUM_TEXT_MARGIN_X,
									LABEL_ID16_SENS_5_NUM_TEXT_MARGIN_Y,
									LABEL_ID16_SENS_5_NUM_ACTION_PTR);
	GUI_createLabel(LABEL_ID17_SENS_6_NUM_X0,	LABEL_ID17_SENS_6_NUM_X1,
									LABEL_ID17_SENS_6_NUM_Y0,	LABEL_ID17_SENS_6_NUM_Y1,
									LABEL_ID17_SENS_6_NUM_BORDER,
									LABEL_ID17_SENS_6_NUM_MAIN_COLOR,
									LABEL_ID17_SENS_6_NUM_BORDER_COLOR,
									LABEL_ID17_SENS_6_NUM_TEXT,
									LABEL_ID17_SENS_6_NUM_TEXT_COLOR,
									LABEL_ID17_SENS_6_NUM_TEXT_MARGIN_X,
									LABEL_ID17_SENS_6_NUM_TEXT_MARGIN_Y,
									LABEL_ID17_SENS_6_NUM_ACTION_PTR);
	GUI_createLabel(LABEL_ID18_SENS_7_NUM_X0,	LABEL_ID18_SENS_7_NUM_X1,
									LABEL_ID18_SENS_7_NUM_Y0,	LABEL_ID18_SENS_7_NUM_Y1,
									LABEL_ID18_SENS_7_NUM_BORDER,
									LABEL_ID18_SENS_7_NUM_MAIN_COLOR,
									LABEL_ID18_SENS_7_NUM_BORDER_COLOR,
									LABEL_ID18_SENS_7_NUM_TEXT,
									LABEL_ID18_SENS_7_NUM_TEXT_COLOR,
									LABEL_ID18_SENS_7_NUM_TEXT_MARGIN_X,
									LABEL_ID18_SENS_7_NUM_TEXT_MARGIN_Y,
									LABEL_ID18_SENS_7_NUM_ACTION_PTR);
	GUI_createLabel(LABEL_ID19_SENS_8_NUM_X0,	LABEL_ID19_SENS_8_NUM_X1,
									LABEL_ID19_SENS_8_NUM_Y0,	LABEL_ID19_SENS_8_NUM_Y1,
									LABEL_ID19_SENS_8_NUM_BORDER,
									LABEL_ID19_SENS_8_NUM_MAIN_COLOR,
									LABEL_ID19_SENS_8_NUM_BORDER_COLOR,
									LABEL_ID19_SENS_8_NUM_TEXT,
									LABEL_ID19_SENS_8_NUM_TEXT_COLOR,
									LABEL_ID19_SENS_8_NUM_TEXT_MARGIN_X,
									LABEL_ID19_SENS_8_NUM_TEXT_MARGIN_Y,
									LABEL_ID19_SENS_8_NUM_ACTION_PTR);
	GUI_createLabel(LABEL_ID20_TSET_NUM_X0,	LABEL_ID20_TSET_NUM_X1,
									LABEL_ID20_TSET_NUM_Y0,	LABEL_ID20_TSET_NUM_Y1,
									LABEL_ID20_TSET_NUM_BORDER,
									LABEL_ID20_TSET_NUM_MAIN_COLOR,
									LABEL_ID20_TSET_NUM_BORDER_COLOR,
									LABEL_ID20_TSET_NUM_TEXT,
									LABEL_ID20_TSET_NUM_TEXT_COLOR,
									LABEL_ID20_TSET_NUM_TEXT_MARGIN_X,
									LABEL_ID20_TSET_NUM_TEXT_MARGIN_Y,
									LABEL_ID20_TSET_NUM_ACTION_PTR);
	GUI_createLabel(LABEL_ID21_TCHANGE_NUM_X0,	LABEL_ID21_TCHANGE_NUM_X1,
									LABEL_ID21_TCHANGE_NUM_Y0,	LABEL_ID21_TCHANGE_NUM_Y1,
									LABEL_ID21_TCHANGE_NUM_BORDER,
									LABEL_ID21_TCHANGE_NUM_MAIN_COLOR,
									LABEL_ID21_TCHANGE_NUM_BORDER_COLOR,
									LABEL_ID21_TCHANGE_NUM_TEXT,
									LABEL_ID21_TCHANGE_NUM_TEXT_COLOR,
									LABEL_ID21_TCHANGE_NUM_TEXT_MARGIN_X,
									LABEL_ID21_TCHANGE_NUM_TEXT_MARGIN_Y,
									LABEL_ID21_TCHANGE_NUM_ACTION_PTR);
	GUI_createLabel(LABEL_ID22_STATE_X0,	LABEL_ID22_STATE_X1,
									LABEL_ID22_STATE_Y0,	LABEL_ID22_STATE_Y1,
									LABEL_ID22_STATE_BORDER,
									LABEL_ID22_STATE_MAIN_COLOR,
									LABEL_ID22_STATE_BORDER_COLOR,
									LABEL_ID22_STATE_TEXT,
									LABEL_ID22_STATE_TEXT_COLOR,
									LABEL_ID22_STATE_TEXT_MARGIN_X,
									LABEL_ID22_STATE_TEXT_MARGIN_Y,
									LABEL_ID22_STATE_ACTION_PTR);

	GUI_createButton(BUTTON_ID0_TPLUS_X0,	BUTTON_ID0_TPLUS_X1,
									BUTTON_ID0_TPLUS_Y0,	BUTTON_ID0_TPLUS_Y1,
									BUTTON_ID0_TPLUS_BORDER,
									BUTTON_ID0_TPLUS_MAIN_COLOR,
									BUTTON_ID0_TPLUS_BORDER_COLOR,
									BUTTON_ID0_TPLUS_TEXT,
									BUTTON_ID0_TPLUS_TEXT_COLOR,
									BUTTON_ID0_TPLUS_TEXT_MARGIN_X,
									BUTTON_ID0_TPLUS_TEXT_MARGIN_Y,
									BUTTON_ID0_TPLUS_STATE,
									BUTTON_ID0_TPLUS_DELAY_SEC,
									BUTTON_ID0_TPLUS_ACTION_PTR);
	GUI_createButton(BUTTON_ID1_TMINUS_X0,	BUTTON_ID1_TMINUS_X1,
									BUTTON_ID1_TMINUS_Y0,		BUTTON_ID1_TMINUS_Y1,
									BUTTON_ID1_TMINUS_BORDER,
									BUTTON_ID1_TMINUS_MAIN_COLOR,
									BUTTON_ID1_TMINUS_BORDER_COLOR,
									BUTTON_ID1_TMINUS_TEXT,
									BUTTON_ID1_TMINUS_TEXT_COLOR,
									BUTTON_ID1_TMINUS_TEXT_MARGIN_X,
									BUTTON_ID1_TMINUS_TEXT_MARGIN_Y,
									BUTTON_ID1_TMINUS_STATE,
									BUTTON_ID1_TMINUS_DELAY_SEC,
									BUTTON_ID1_TMINUS_ACTION_PTR);
	GUI_createButton(BUTTON_ID2_SWITCHER_X0,	BUTTON_ID2_SWITCHER_X1,
									BUTTON_ID2_SWITCHER_Y0,		BUTTON_ID2_SWITCHER_Y1,
									BUTTON_ID2_SWITCHER_BORDER,
									BUTTON_ID2_SWITCHER_MAIN_COLOR,
									BUTTON_ID2_SWITCHER_BORDER_COLOR,
									BUTTON_ID2_SWITCHER_TEXT,
									BUTTON_ID2_SWITCHER_TEXT_COLOR,
									BUTTON_ID2_SWITCHER_TEXT_MARGIN_X,
									BUTTON_ID2_SWITCHER_TEXT_MARGIN_Y,
									BUTTON_ID2_SWITCHER_STATE,
									BUTTON_ID2_SWITCHER_DELAY_SEC,
									BUTTON_ID2_SWITCHER_ACTION_PTR);
	
	LCD_printChar(GUI.objList.ObjLabelList[LABEL_HEADER_ID].textLenght, LABEL_ID0_HEADER_Y0-2, '2', 0xFFFF, impact_18ptBitmapsNum, impact_18ptDescriptorsNum, DESCRIPTORSBLOCK0_OFFSET);

	GUI_CTC_buttonTPlusDraw(BUTTON_ID0_TPLUS_MAIN_COLOR);
	GUI_CTC_buttonTMinusDraw(BUTTON_ID1_TMINUS_MAIN_COLOR);
	
	GUI_drawFrame(0, LABEL_ID1_HEADER_SENS_X1, 0, LABEL_ID0_HEADER_Y0+1, 2, 0x0000);
	GUI_drawFrame(0, LCD_WIDTH-1, 0, LCD_HEIGHT-1, 2, 0x0000);
}


void	GUI_CTC_buttonStateClick(void)
{
	if(GUI.objList.ObjButtonList[BUTTON_SWITCHER_ID].state == 0)
	{
		GUI.objList.ObjButtonList[BUTTON_SWITCHER_ID].state = 1;
		GUI_buttonChangeMainColor(BUTTON_SWITCHER_ID, BUTTON_SWITCHER_MAIN_COLOR_1);
		GUI_buttonChangeText(BUTTON_SWITCHER_ID, BUTTON_SWITCHER_TEXT_1, 0x0000);
		GUI_CTC_labelState(LABEL_STATE_ID, 1);
	}
	else
	{
		GUI.objList.ObjButtonList[BUTTON_SWITCHER_ID].state = 0;
		GUI_buttonChangeMainColor(BUTTON_SWITCHER_ID, BUTTON_SWITCHER_MAIN_COLOR_0);
		GUI_buttonChangeText(BUTTON_SWITCHER_ID, BUTTON_SWITCHER_TEXT_0, 0x0000);
		GUI_CTC_labelState(LABEL_STATE_ID, 0);
	}
}

void	GUI_CTC_labelState(uint8_t labelNum,	uint8_t state)
{
	if(state == 0)
	{
		GUI_labelChangeMainColor(labelNum, LABEL_STATE_MAIN_COLOR_0);
		GUI_labelChangeText(labelNum, LABEL_STATE_TEXT_0, 0x0000);
	}
	else
	{
		GUI_labelChangeMainColor(labelNum, LABEL_STATE_MAIN_COLOR_1);
		GUI_labelChangeText(labelNum, LABEL_STATE_TEXT_1, 0x0000);
	}
}


void	GUI_CTC_buttonTPlusDraw(uint16_t mainColor)
{
	GUI_buttonChangeMainColor(BUTTON_TPLUS_ID, mainColor);
	
	GUI_drawFilledFrame(BUTTON_ID0_TPLUS_X0+47, BUTTON_ID0_TPLUS_X1-47, BUTTON_ID0_TPLUS_Y0+5, BUTTON_ID0_TPLUS_Y1-5, 0, 0xFFFF, 0xFFFF);
	GUI_drawFilledFrame(BUTTON_ID0_TPLUS_X0+30, BUTTON_ID0_TPLUS_X1-30, BUTTON_ID0_TPLUS_Y0+22, BUTTON_ID0_TPLUS_Y1-22, 0, 0xFFFF, 0xFFFF);
}

void	GUI_CTC_buttonTPlusClick(void)
{
	GUI_CTC_buttonTPlusDraw(BUTTON_TPLUS_CLICK_COLOR);
	tempSetNum++;
	GUI_CTC_labelTSetNum(LABEL_TSET_NUM_ID, &strBufNum[0], tempSetNum);
}

void	GUI_CTC_buttonTPlusReturnColor(void)
{
	if(GUI.objList.ObjButtonList[BUTTON_TPLUS_ID].flag_buttonWasClicked == 0 && GUI.objList.ObjButtonList[BUTTON_TPLUS_ID].mainColor != BUTTON_ID0_TPLUS_MAIN_COLOR)
		GUI_CTC_buttonTPlusDraw(BUTTON_ID0_TPLUS_MAIN_COLOR);
}


void	GUI_CTC_buttonTMinusDraw(uint16_t mainColor)
{
	GUI_buttonChangeMainColor(BUTTON_TMINUS_ID, mainColor);
	
	GUI_drawFilledFrame(BUTTON_ID1_TMINUS_X0+30, BUTTON_ID1_TMINUS_X1-30, BUTTON_ID1_TMINUS_Y0+22, BUTTON_ID1_TMINUS_Y1-22, 0, 0xFFFF, 0xFFFF);
}

void	GUI_CTC_buttonTMinusClick(void)
{
	GUI_CTC_buttonTMinusDraw(BUTTON_TMINUS_CLICK_COLOR);
	tempSetNum--;
	GUI_CTC_labelTSetNum(LABEL_TSET_NUM_ID, &strBufNum[0], tempSetNum);
}

void	GUI_CTC_buttonTMinusReturnColor(void)
{
	if(GUI.objList.ObjButtonList[BUTTON_TMINUS_ID].flag_buttonWasClicked == 0 && GUI.objList.ObjButtonList[BUTTON_TMINUS_ID].mainColor != BUTTON_ID1_TMINUS_MAIN_COLOR)
		GUI_CTC_buttonTMinusDraw(BUTTON_ID1_TMINUS_MAIN_COLOR);
}


void	GUI_CTC_labelTSetNum(uint8_t labelNum, char *str, int32_t setNum)
{
	GUI_intToStr(setNum, str);
	GUI_labelChangeText(labelNum, str, 0x0000);
}


void	GUI_CTC_objAction(void)
{
	GUI_CTC_buttonTPlusReturnColor();
	GUI_CTC_buttonTMinusReturnColor();
}
